# График движения цены после свечи в выбранным кодом по Лиховидову

In [1]:
import pandas as pd

In [2]:
# Загружаем файл с разделителем ',' в DF, индексом делаем поле 'date_time'
df = pd.read_csv('c:\data_prepare_quote_csv\SPFB.RTS_5min_2020-09-01_2020-11-10_lihovidov.csv', delimiter=',')
df = df.set_index(pd.to_datetime(df['date_time'], format='%Y-%m-%d %H:%M:%S'))  # Меняем индекс и делаем его типом datetime
df = df.drop('date_time', 1)  # Удаляем колонку с датой и временем, т.к. дата-время у нас теперь в индексе
df

,date,time,open,high,low,close,vol,candle_code
date_time,,,,,,,,
2020-09-01 10:00:00,20200901,100000,126200.0,127210.0,126200.0,127030.0,24238,107.0
2020-09-01 10:05:00,20200901,100500,127030.0,127320.0,127000.0,127120.0,16623,94.0
2020-09-01 10:10:00,20200901,101000,127130.0,127180.0,126820.0,127160.0,9791,84.0
2020-09-01 10:15:00,20200901,101500,127170.0,127380.0,127090.0,127180.0,13324,93.0
2020-09-01 10:20:00,20200901,102000,127190.0,127640.0,127190.0,127490.0,11582,127.0
...,...,...,...,...,...,...,...,...
2020-11-10 23:25:00,20201110,232500,123270.0,123330.0,123190.0,123290.0,844,92.0
2020-11-10 23:30:00,20201110,233000,123300.0,123300.0,123190.0,123210.0,728,1.0
2020-11-10 23:35:00,20201110,233500,123200.0,123200.0,123100.0,123110.0,1418,2.0
2020-11-10 23:40:00,20201110,234000,123120.0,123210.0,123110.0,123190.0,879,106.0
2020-11-10 23:45:00,20201110,234500,123190.0,123290.0,123130.0,123200.0,2370,93.0

In [3]:
# Создаем DF с заданным кодом
df_candle_code = df.query('candle_code == 0')
print(df_candle_code.shape)
# df_candle_code

(35, 8)

In [5]:
# Перебираем строки DF df_candle_code
for index, row in df_candle_code.iterrows():  # Перебираем строки dataframe df_candle_code
    df_posl = df[index:].head(20)  # Создаем последующий DF
    
    price_at_t0 = df_posl.iloc[0, 5]  # Берем самое первое по времени значение (к нему нормализуем)
    df_posl[index] = df_posl.apply(lambda row: row['close'] / price_at_t0, axis=1)  # axis=1 Указывает на колонку
    
    print(df_posl)
    break

                         date    time      open      high       low     close  \
date_time
2020-09-04 14:10:00  20200904  141000  122930.0  122930.0  122580.0  122730.0
2020-09-04 14:15:00  20200904  141500  122730.0  122800.0  122560.0  122700.0
2020-09-04 14:20:00  20200904  142000  122680.0  122890.0  122670.0  122840.0
2020-09-04 14:25:00  20200904  142500  122850.0  122860.0  122710.0  122760.0
2020-09-04 14:30:00  20200904  143000  122770.0  122850.0  122620.0  122640.0
2020-09-04 14:35:00  20200904  143500  122640.0  122660.0  122470.0  122480.0
2020-09-04 14:40:00  20200904  144000  122480.0  122560.0  122300.0  122500.0
2020-09-04 14:45:00  20200904  144500  122490.0  122550.0  122420.0  122480.0
2020-09-04 14:50:00  20200904  145000  122470.0  122540.0  122360.0  122500.0
2020-09-04 14:55:00  20200904  145500  122490.0  122520.0  122390.0  122400.0
2020-09-04 15:00:00  20200904  150000  122420.0  122670.0  122400.0  122640.0
2020-09-04 15:05:00  20200904  150500  122650.0  122690.0  122380.0  122390.0
2020-09-04 15:10:00  20200904  151000  122410.0  122460.0  122300.0  122420.0
2020-09-04 15:15:00  20200904  151500  122430.0  122610.0  122430.0  122550.0
2020-09-04 15:20:00  20200904  152000  122540.0  122830.0  122540.0  122810.0
2020-09-04 15:25:00  20200904  152500  122810.0  122900.0  122690.0  122770.0
2020-09-04 15:30:00  20200904  153000  122750.0  123040.0  122660.0  122860.0
2020-09-04 15:35:00  20200904  153500  122860.0  122860.0  122460.0  122540.0
2020-09-04 15:40:00  20200904  154000  122540.0  122790.0  122490.0  122780.0
2020-09-04 15:45:00  20200904  154500  122790.0  122960.0  122730.0  122860.0

                       vol  candle_code  2020-09-04 14:10:00
date_time
2020-09-04 14:10:00   7149          0.0             1.000000
2020-09-04 14:15:00   4689         40.0             0.999756
2020-09-04 14:20:00   3224        122.0             1.000896
2020-09-04 14:25:00   1530         21.0             1.000244
2020-09-04 14:30:00   2514         30.0             0.999267
2020-09-04 14:35:00   4348          6.0             0.997963
2020-09-04 14:40:00   6569         88.0             0.998126
2020-09-04 14:45:00   2682         41.0             0.997963
2020-09-04 14:50:00   3220         88.0             0.998126
2020-09-04 14:55:00   2715         22.0             0.997311
2020-09-04 15:00:00   4219        118.0             0.999267
2020-09-04 15:05:00   3466         10.0             0.997230
2020-09-04 15:10:00   3736         88.0             0.997474
2020-09-04 15:15:00   2452        107.0             0.998533
2020-09-04 15:20:00   4041        119.0             1.000652
2020-09-04 15:25:00   4734         44.0             1.000326
2020-09-04 15:30:00  12476        108.0             1.001059
2020-09-04 15:35:00   6085          0.0             0.998452
2020-09-04 15:40:00   3276        117.0             1.000407
2020-09-04 15:45:00   4263        109.0             1.001059