# Проверка сохраненного файла candle code

In [14]:
import pandas as pd

In [15]:
# Загружаем файл с разделителем ';' в DF, индексом делаем поле 'date_time'
df = pd.read_csv('c:\data_prepare_quote_csv\SPFB.RTS_5min_2020-09-01_2020-11-10_lihovidov.csv', delimiter=',')
df = df.set_index(pd.to_datetime(df['date_time'], format='%Y-%m-%d %H:%M:%S'))  # Меняем индекс и делаем его типом datetime
# df = df.drop('date_time', 1)  # Удаляем колонку с датой и временем, т.к. дата-время у нас теперь в индексе
df

,date_time,date,time,open,high,low,close,vol,candle_code
date_time,,,,,,,,,
2020-09-01 10:00:00,2020-09-01 10:00:00,20200901,100000,126200.0,127210.0,126200.0,127030.0,24238,107.0
2020-09-01 10:05:00,2020-09-01 10:05:00,20200901,100500,127030.0,127320.0,127000.0,127120.0,16623,94.0
2020-09-01 10:10:00,2020-09-01 10:10:00,20200901,101000,127130.0,127180.0,126820.0,127160.0,9791,84.0
2020-09-01 10:15:00,2020-09-01 10:15:00,20200901,101500,127170.0,127380.0,127090.0,127180.0,13324,93.0
2020-09-01 10:20:00,2020-09-01 10:20:00,20200901,102000,127190.0,127640.0,127190.0,127490.0,11582,127.0
...,...,...,...,...,...,...,...,...,...
2020-11-10 23:25:00,2020-11-10 23:25:00,20201110,232500,123270.0,123330.0,123190.0,123290.0,844,92.0
2020-11-10 23:30:00,2020-11-10 23:30:00,20201110,233000,123300.0,123300.0,123190.0,123210.0,728,1.0
2020-11-10 23:35:00,2020-11-10 23:35:00,20201110,233500,123200.0,123200.0,123100.0,123110.0,1418,2.0
2020-11-10 23:40:00,2020-11-10 23:40:00,20201110,234000,123120.0,123210.0,123110.0,123190.0,879,106.0
2020-11-10 23:45:00,2020-11-10 23:45:00,20201110,234500,123190.0,123290.0,123130.0,123200.0,2370,93.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8020 entries, 2020-09-01 10:00:00 to 2020-11-10 23:45:00
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date_time    8020 non-null   object
 1   date         8020 non-null   int64
 2   time         8020 non-null   int64
 3   open         8020 non-null   float64
 4   high         8020 non-null   float64
 5   low          8020 non-null   float64
 6   close        8020 non-null   float64
 7   vol          8020 non-null   int64
 8   candle_code  8020 non-null   float64
dtypes: float64(5), int64(3), object(1)
memory usage: 626.6+ KB

In [17]:
df.describe()

,date,time,open,high,low,close,vol,candle_code
count,8.020000e+03,8020.000000,8020.000000,8020.000000,8020.000000,8020.000000,8020.000000,8020.000000
mean,2.020098e+07,166377.867830,116764.457606,116862.293017,116666.740648,116764.396509,3701.230923,64.783416
std,6.612929e+01,40241.313068,4700.653410,4697.470850,4703.737700,4699.978718,3598.022353,38.831988
min,2.020090e+07,100000.000000,103760.000000,104050.000000,103610.000000,103760.000000,4.000000,0.000000
25%,2.020092e+07,132000.000000,114340.000000,114430.000000,114260.000000,114340.000000,1278.250000,27.000000
50%,2.020101e+07,164500.000000,116000.000000,116100.000000,115910.000000,116000.000000,2764.000000,72.000000
75%,2.020102e+07,202500.000000,120420.000000,120502.500000,120330.000000,120410.000000,5001.000000,101.000000
max,2.020111e+07,234500.000000,128210.000000,128240.000000,128060.000000,128230.000000,47420.000000,127.000000

In [18]:
df.groupby('candle_code').count()

             date_time  date  time  open  high  low  close  vol
candle_code
0.0                 35    35    35    35    35   35     35   35
1.0                 63    63    63    63    63   63     63   63
2.0                 53    53    53    53    53   53     53   53
3.0                 19    19    19    19    19   19     19   19
4.0                 69    69    69    69    69   69     69   69
...                ...   ...   ...   ...   ...  ...    ...  ...
123.0               58    58    58    58    58   58     58   58
124.0               17    17    17    17    17   17     17   17
125.0               33    33    33    33    33   33     33   33
126.0               62    62    62    62    62   62     62   62
127.0               43    43    43    43    43   43     43   43

[115 rows x 8 columns]

In [19]:
df_0 = df.query('candle_code == 0')
print(df_0.shape)
df_0

(35, 9)

,date_time,date,time,open,high,low,close,vol,candle_code
date_time,,,,,,,,,
2020-09-04 14:10:00,2020-09-04 14:10:00,20200904,141000,122930.0,122930.0,122580.0,122730.0,7149,0.0
2020-09-04 15:35:00,2020-09-04 15:35:00,20200904,153500,122860.0,122860.0,122460.0,122540.0,6085,0.0
2020-09-04 23:35:00,2020-09-04 23:35:00,20200904,233500,123000.0,123000.0,122820.0,122860.0,877,0.0
2020-09-08 16:40:00,2020-09-08 16:40:00,20200908,164000,118840.0,118840.0,118310.0,118500.0,14135,0.0
2020-09-10 11:40:00,2020-09-10 11:40:00,20200910,114000,117610.0,117610.0,117250.0,117420.0,621,0.0
2020-09-11 16:55:00,2020-09-11 16:55:00,20200911,165500,120700.0,120700.0,120390.0,120500.0,702,0.0
2020-09-21 10:30:00,2020-09-21 10:30:00,20200921,103000,120100.0,120100.0,119600.0,119740.0,9425,0.0
2020-09-21 21:05:00,2020-09-21 21:05:00,20200921,210500,116960.0,116960.0,116730.0,116850.0,1675,0.0
2020-09-23 17:35:00,2020-09-23 17:35:00,20200923,173500,117990.0,117990.0,117650.0,117740.0,15911,0.0
2020-09-23 21:00:00,2020-09-23 21:00:00,20200923,210000,117550.0,117550.0,117270.0,117380.0,6496,0.0
2020-09-24 17:30:00,2020-09-24 17:30:00,20200924,173000,116710.0,116710.0,116190.0,116390.0,11794,0.0
2020-09-24 20:55:00,2020-09-24 20:55:00,20200924,205500,117410.0,117410.0,117210.0,117280.0,2455,0.0
2020-09-24 23:25:00,2020-09-24 23:25:00,20200924,232500,116760.0,116760.0,116650.0,116690.0,545,0.0
2020-09-25 17:55:00,2020-09-25 17:55:00,20200925,175500,115150.0,115150.0,114900.0,114990.0,4258,0.0
2020-09-28 16:25:00,2020-09-28 16:25:00,20200928,162500,115800.0,115800.0,115500.0,115610.0,5203,0.0
2020-09-30 10:45:00,2020-09-30 10:45:00,20200930,104500,114640.0,114640.0,114240.0,114390.0,11075,0.0
2020-10-01 13:45:00,2020-10-01 13:45:00,20201001,134500,116610.0,116610.0,116320.0,116420.0,4421,0.0
2020-10-01 16:05:00,2020-10-01 16:05:00,20201001,160500,116780.0,116780.0,116410.0,116500.0,11475,0.0
2020-10-01 20:55:00,2020-10-01 20:55:00,20201001,205500,115850.0,115850.0,115640.0,115720.0,2892,0.0
2020-10-02 10:00:00,2020-10-02 10:00:00,20201002,100000,115590.0,115590.0,114000.0,114340.0,22899,0.0
2020-10-02 19:00:00,2020-10-02 19:00:00,20201002,190000,114410.0,114410.0,113850.0,114180.0,5713,0.0
2020-10-07 21:05:00,2020-10-07 21:05:00,20201007,210500,114490.0,114490.0,114330.0,114380.0,1547,0.0
2020-10-09 10:55:00,2020-10-09 10:55:00,20201009,105500,115340.0,115340.0,115000.0,115150.0,12899,0.0
2020-10-19 21:45:00,2020-10-19 21:45:00,20201019,214500,112380.0,112380.0,112200.0,112280.0,5513,0.0
2020-10-26 19:45:00,2020-10-26 19:45:00,20201026,194500,114410.0,114410.0,114030.0,114200.0,7249,0.0
2020-10-28 11:45:00,2020-10-28 11:45:00,20201028,114500,109930.0,109930.0,109560.0,109710.0,12536,0.0
2020-10-28 12:00:00,2020-10-28 12:00:00,20201028,120000,109620.0,109620.0,109060.0,109160.0,16640,0.0
2020-10-28 13:10:00,2020-10-28 13:10:00,20201028,131000,109120.0,109120.0,108870.0,108950.0,5451,0.0
2020-10-28 18:30:00,2020-10-28 18:30:00,20201028,183000,107660.0,107660.0,107360.0,107460.0,7136,0.0
2020-10-30 13:40:00,2020-10-30 13:40:00,20201030,134000,106860.0,106860.0,106540.0,106720.0,7324,0.0
2020-10-30 18:15:00,2020-10-30 18:15:00,20201030,181500,106630.0,106630.0,106390.0,106470.0,3764,0.0
2020-11-02 10:15:00,2020-11-02 10:15:00,20201102,101500,104790.0,104790.0,104200.0,104460.0,11146,0.0
2020-11-06 16:05:00,2020-11-06 16:05:00,20201106,160500,115750.0,115750.0,115450.0,115530.0,3999,0.0
2020-11-09 23:20:00,2020-11-09 23:20:00,20201109,232000,122560.0,122560.0,122410.0,122490.0,1520,0.0
2020-11-10 12:50:00,2020-11-10 12:50:00,20201110,125000,122980.0,122980.0,122720.0,122840.0,4062,0.0